# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'Grocery List Pro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grocery List Pro
    pod 'Firebase/Core'



  target 'Grocery List ProTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Grocery List ProUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
