# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Magic Pantry' do
  use_frameworks!

  # Pods for Magic Pantry
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  pod 'Firebase/Analytics'

  pod 'paper-onboarding'
  pod 'BulletinBoard'

  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Phone'

  target 'Magic PantryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Magic PantryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

platform :ios, '13.0' # set IPHONEOS_DEPLOYMENT_TARGET for the pods project
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
